### ISSUE TITLE
Support with base16-shell and base16-vim

### ISSUE THREAD

**Issue by acroz** [chriskempson/base16-vim#119]
I am a long time user of base16-shell and recently updated my dotfiles to use this vim extension too. I really love these packages - thanks a lot for your contribution to the community!

I'm having a little trouble with the vim colour scheme that I hope you can help me with. With a base16-shell colour scheme active, I am loading base16-vim with Vundle, and have the following snippet in place to load the colour scheme in my .vimrc:

``` vim
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
```

However, while changing the colour scheme changes the colours displayed by vim-airline, the file content text colours appear to be unchanged. Indeed, when I compared the colours against your [nice preview page](https://chriskempson.github.io/base16/), the colours appear to be quite different. The following image compares my colours against your preview page for base16-default-dark:

![screenshot from 2016-10-18 11-17-59](https://cloud.githubusercontent.com/assets/1584318/19473709/9c5b01c4-9524-11e6-8782-afb2dcb3def4.png)

I am using gnome-terminal with terminal vim. Here is the result of colortest in the shell:

![screenshot from 2016-10-18 11-19-53](https://cloud.githubusercontent.com/assets/1584318/19473848/287d455e-9525-11e6-87dc-6c1f8df260c1.png)

I would appreciate any help you can provide in fixing my configuration!

**Comment by nerfologist** [comment]
Hi,
I did some research on this issue myself (using base16-materia). Please note that I am a newbie to Vim hacking so the following explaination just reflects my (possibly faulty) understanding.

It turns out that the base16 colorscheme associates the default highlight group `Identifier` with the red color:
```vimscript
" colors/base16-materia.vim
call <sid>hi("Identifier",   s:gui08, "", s:cterm08, "", "none", "")
```
You can see this in practice with instance variables.

So the reason why Ruby local variables (and methods) do not appear to be highlighted is that, for some reason, they are not linked to the `Identifier` group.

The reason for this is to be found in the ruby syntax file:
```vimscript
" syntax/ruby.vim
syn match rubyLocalVariableOrMethod "\<[_[:lower:]][_[:alnum:]]*[?!=]\=" contains=NONE display transparent
```
This line tells Vim how to identify a ruby local variable or method, sets a few options and specifies that a local variable or method should inherit the highlighting of the containing section.

If you want to display local identifiers in red, similar to the preview page, you should remove the `transparent` option (stop getting the same color as the container):
```vimscript
" syntax/ruby.vim
syn match rubyLocalVariableOrMethod "\<[_[:lower:]][_[:alnum:]]*[?!=]\=" contains=NONE display
```
And in the bottom part of the syntax file you should link `rubyLocalVariableOrMethod` to `rubyIdentifier`s
```vimscript
hi def link rubyLocalVariableOrMethod   rubyIdentifier
```
Note that `rubyIdentifier`s are already linked to `Identifier`s:
```vimscript
if !exists("ruby_no_identifiers")
  hi def link rubyIdentifier		Identifier
else
  hi def link rubyIdentifier		NONE
endif
```
This should turn all local identifiers to red (at least, it did on my machine!).
HTH

**Comment by chriskempson** [comment]
This is perfectly normal. The preview isn't a preview or Vim or any other editor for that matter. It's merely a preview of how the theme should look. In practise most editors have limitations that have the be taken into consideration.
