### ISSUE TITLE
Regression: Not functional anymore on vim 7.3.547 starting at 3fd9fbd13455a8e6adb7b9cf0fa0a39fa46fea8c

### ISSUE THREAD

**Issue by 2ion** [chriskempson/base16-vim#162]
(This is on a non-upgradable Wheezy container).

 * vim: 2:7.3.547-7+deb7u1
 * Last good checkout: 9382428078e6562ca687476e5f2e4b262cec5623
 * Plugins: base16-vim,  tabular,  vim-airline,  vim-airline-themes,  vim-fugitive,  vim-puppet,  vim-repeat,  vim-sleuth,  vim-startify,  vim-surround. Always latest git checkouts.
 * vimrc & vimrc_background: [Gist](https://gist.github.com/2ion/cba002bbf41aa845a57aacb6a9c7ae90)

Starting with 3fd9fbd13455a8e6adb7b9cf0fa0a39fa46fea8c, vim just spews
```
Error detected while processing function <SNR>13_hi:
line    1:
E117: Unknown function: Base16hi
```
and obviously fails to apply the theme. Previous versions worked fine.

**Comment by h404bi** [comment]
met the same issue. I use this workaround:
```
$ cd ~/.vim/bundle/base16-vim
$ git checkout 938242
```

**Comment by mclang** [comment]
I had the same problem.

If checking out old version is not possible, edit e.g `base16-vim/colors/base16-default-dark.vim` and remove `g:` from the function definition:
```
" Highlighting function
- function! g:Base16hi(group, guifg, guibg, ctermfg, ctermbg, attr, guisp)
+ function! Base16hi(group, guifg, guibg, ctermfg, ctermbg, attr, guisp)
```

**Comment by chriskempson** [comment]
Seems the template changes made in https://github.com/chriskempson/base16-vim/commit/f703015dc0137d79379492ae61e78efbb7ecf512#diff-943b25eef6424ea03043b2f72553fd92 by @jlesquembre don't work with older versions of Vim.

**Comment by jlesquembre** [comment]
Sorry for the bug. I think the problem is the `g:` (global variable). It is possible to remove it on the function declaration ([link](https://github.com/chriskempson/base16-vim/blob/dfe039591ab935803de0c028a2be859a5a425611/templates/default.mustache#L132)) or add it when the function is called ([link](https://github.com/chriskempson/base16-vim/blob/dfe039591ab935803de0c028a2be859a5a425611/templates/default.mustache#L155)). Both solutions work on modern (neo)vim, not sure what is better.

Unfortunately I don't know an easy way of testing it on an old vim version, can anyone confirm if both solutions work on old vim versions?

**Comment by mrksr** [comment]
I have just tried both of your proposed fixes on a vim installation which is affected and they both seem to work.

```shell
> vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 20 2017 04:38:11)
Included patches: 1-160
```
