### ISSUE TITLE
Using named colors only

### ISSUE THREAD

**Issue by jswny** [chriskempson/base16-vim#208]
Forgive me if I'm misunderstanding the concept of Base 16, but after reading [this issue](https://github.com/chriskempson/base16/issues/174), I was under the impression that you could setup Base 16 so that the themes would use only the 16 ANSI named colors like `white`, `brred`, etc (or the 256 named colors). That way, you could set the color scheme in your terminal and Base 16 Vim would use only named colors, causing vim to be colored like your terminal. 

However, looking through the color scheme definitions in `colors/`, they all use hardcoded hex values, meaning that those colors wouldn't change depending on changes to named colors.

Is there a way to set Base 16 Vim to use named colors only or am I just totally misunderstanding the purpose of Base 16?

Thanks!

**Comment by belak** [comment]
By default base16-vim in the terminal should use the 16 named colors. There are ways of overriding this... and there are also other tricks because only 8 of the 16 colors are really useful for terminals (there are 8 colors and 8 shades of gray), but it should work out of the box.

Here are the setups as I see them:

- Use base16-vim with a base16 terminal scheme.
- Use base16-vim in gui mode
- Use base16-vim with a 256 color terminal, a 256 color base16 color scheme, and the corresponding base16-shell theme. This requires setting base16colorspace.

**Comment by jswny** [comment]
@belak Thanks! That definitely clears it up a bit for me. So for for base16-vim to use 256 colors, you must use base16-shell with an appropriate theme set, is that correct?

**Comment by belak** [comment]
It's a bit of a misnomer - base16-shell is a hack that jams the gray colors into colors 17-24 (that way you can have matching colors for normal and bold), so when you set base16colorspace, it will use colors 17-24... so that naturally only works if you're also using base16-shell.

**Comment by belak** [comment]
It's more different options depending on which variant of the terminal color scheme you want to use.

**Comment by jswny** [comment]
@belak Ok I see now. My last question would be if I am using base16-vim with a base16 terminal scheme, do I need to set something like `colorscheme base16-solarized-dark` in my `.vimrc`? If so, why would I need to set a specific scheme considering the advantage of this setup is that the scheme is defined by my terminal?

Thanks for the help!

**Comment by belak** [comment]
If you're using a base16 terminal scheme and you're either not using the 256 color variant or using base16-shell, all base16 schemes in vim should have the identical result.
