### ISSUE TITLE
Color issue with Vim8 terminal

### ISSUE THREAD

**Issue by dyamon** [chriskempson/base16-vim#215]
I seem to have color issues when pulling up a terminal inside Vim.

![screenshot-20200831-202107](https://user-images.githubusercontent.com/6771224/91753713-92f90000-ebc8-11ea-9fe1-43b5886cb3ce.png)

This is st running bash running Vim. Both `base16-shell` and `base16-vim` are used and configured as told in the repos.

Prompt is set with this snippet in my `.bashrc`:

```bash
black=$(tput setaf 0)
red=$(tput setaf 9);
green=$(tput setaf 10);
yellow=$(tput setaf 11);
blue=$(tput setaf 12);
magenta=$(tput setaf 13);
cyan=$(tput setaf 14);
orange=$(tput setaf 166)
white=$(tput setaf 15)
grey=$(tput setaf 8)
bold=$(tput bold);
reset=$(tput sgr0);

PS1=""
## Username
PS1+="\[${bold}\]\[${green}\]\u\[${reset}\]" 
PS1+=" at "
## Hostname
PS1+="\[${bold}\]\[${yellow}\]\h\[${reset}\]"
PS1+=" in "
## Current working directory
PS1+="\[${bold}\]\[${blue}\]\w\[${reset}\]"
## Git prompt
PS1+="\[\$(git_prompt)\]"
PS1+="\n"
## Lambda prompt
PS1+="\[${bold}\]λ\[${reset}\]"

PS1+="\$(job_count) "
export PS1;
```

Running `colortest` in this terminal returns this
![screenshot-20200831-202934](https://user-images.githubusercontent.com/6771224/91754519-d3a54900-ebc9-11ea-888c-560f0d0f395a.png)

Do you have any idea what could be causing this?

**Comment by danielwe** [comment]
I'm running into the same or at least a similar problem. A workaround is to add the following to your `.vimrc` _after_ the `colorscheme base16-...` statement:

```vim
if !&termguicolors && exists('g:terminal_ansi_colors')
  unlet g:terminal_ansi_colors
endif
```

### What's actually going on?

* base16_vim sets `g:terminal_ansi_colors` so that the vim terminal will inherit the base16 colorscheme to the extent possible
* vim messes up when `g:terminal_ansi_colors` is set without `termguicolors` being set. This is the typical combination when using base16-shell and base16-vim together. The result is that the whole ANSI palette is thrown out, as your colortest is showing.
* This is a recent bug in vim. The documentation (see `:h terminal_ansi_colors`) explicitly states that "When not using GUI colors, the terminal window always uses the 16 ANSI colors of
the underlying terminal", which is exactly what we would want; `g:terminal_ansi_colors` only makes sense in gvim or when `termguicolors` is set, and should be ignored otherwise. The actual behavior seems to fluctuate a lot between versions and depends on the value of `t_Co`, see https://github.com/vim/vim/issues/5993.
* A pretty robust fix from the base16_vim side would be to only set `g:terminal_ansi_colors` when `termguicolors` is set. I'd make a pull request, but I'm afraid this repo is dying :worried:
* Disclaimer: Our issues might not be identical, I don't get the big dump of color codes at the top of the newly opened terminal shown in your screenshot, but otherwise it looks very similar.

**Comment by dyamon** [comment]
Thanks for the reply!

I can confirm that this workaround indeed fixes the problem. I had to put the snippet way down in my `.vimrc`. I'm loading plugins with `packadd!` and I need to put the snippet after these calls for it to be effective (or possibly somewhere called later on).

> * A pretty robust fix from the base16_vim side would be to only set `g:terminal_ansi_colors` when `termguicolors` is set. I'd make a pull request, but I'm afraid this repo is dying.
Probably, for me the easiest way would be to ditch base16 completely and handle colors from st directly. It would spare me a plugin and a bunch of settings here and there.

> * Disclaimer: Our issues might not be identical, I don't get the big dump of color codes at the top of the newly opened terminal shown in your screenshot, but otherwise it looks very similar.
As you said the colors are fixed but the color codes are still there. I guess it is something weird happening with my `.bashrc`.

**Comment by dyamon** [comment]
Closing because [this](https://github.com/chriskempson/base16-vim/issues/215#issuecomment-729954929) is the solution.

The dump of color codes before the user prompt was casued by a hack I introduced in my `.bashrc` to solve an unrelated problem.
