### ISSUE TITLE
Ubuntu 14.04, Terminator, Vim

### ISSUE THREAD

**Issue by FrigoEU** [chriskempson/base16-vim#52]
Hey,

 I can't seem to get this color scheme to work on my setup with Ubuntu 1.04, Terminator and Vim. I set Terminator's palette to the exact colors:

palette = "#151515:#202020:#303030:#505050:#b0b0b0:#d0d0d0:#e0e0e0:#f5f5f5:#ac4142:#d28445:#f4bf75:#90a959:#75b5aa:#6a9fb5:#aa759f:#8f5536"

 added the Vim colors and adjusted my vimrc as such: 

set background=dark
colorscheme base16-default
set t_Co=16

I must be missing something really obvious, but for the life of me I can't figure it out.

**Comment by ashleyblackmore** [comment]
Terminator is really problematic for this, since it doesn't seem to match standards of other terminals (such as Ubuntu default). Try removing the `colorscheme base16-default` line from your vimrc, since what you are effectively doing here is setting colours twice (once in terminator options, and once in vim).

Alternatively, give up all hope and switch to standard terminal + tmux (or go nuclear and use a tiling window manager like awesome, or xmonad)

**Comment by ashleyblackmore** [comment]
I just managed to get this working in terminator with:

`git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell`

Then setting:
`# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL`
in ~/.bashrc

No vim settings required, and defaults in terminator. You may have to pick your own background colour with this option, though.
